#!/bin/bash
# 2560x1440
# Fullscreen
# Vulkan
# Default
# RaiNyMore2 -- GPU-intensive 

PRIME_NO_RUN=1
source prime-run
PRIME_NO_RUN=""

(echo 7; echo 2; echo 1; echo 1; echo 2; echo n) | phoronix-test-suite benchmark pts/ddnet
