#!/bin/bash

NVIDIA_BIN_URL="https://github.com/wanlizhu/NVIDIA_BIN.git"

function devenv-init() {
    # GNOME 
    gsettings set org.gnome.desktop.screensaver lock-enabled false
    gsettings set org.gnome.desktop.screensaver lock-delay 0
    gsettings set org.gnome.desktop.screensaver ubuntu-lock-on-suspend false

    # Linux Perf
    sudo apt install linux-tools-generic -y
    sudo apt install linux-cloud-tools-generic -y
    sudo apt install linux-tools-`uname -r` -y
    sudo apt install linux-cloud-tools-`uname -r` -y

    if [ "$(cat /proc/sys/kernel/perf_event_paranoid)" != "-1" ]; then
        sudo sh -c "echo -1 > /proc/sys/kernel/perf_event_paranoid"
        sudo echo "kernel.perf_event_paranoid = -1" >> /etc/sysctl.conf
    fi

    # Git
    sudo apt install git -y
    sudo apt install gh -y # Use `gh auth login` to store GitHub credential locally
    sudo git config --global user.email wanlizhu@hotmail.com
    sudo git config --global user.name "Wanli Zhu"

    # Tools
    sudo apt install openssh-server -y
    sudo apt install build-essential -y
    sudo apt install cmake -y
    sudo apt install sshfs -y
    sudo apt install vim -y
    sudo apt install net-tools -y
    sudo apt install pkg-config -y
    sudo apt install libglvnd-dev -y
    sudo apt install openconnect -y
    sudo apt install steam -y
    sudo apt install libncurses-dev bison flex libssl-dev libelf-dev 
    sudo apt install screen -y
    sudo apt install mailutils -y
    
    # Git Auth
    gh auth login
    
    # Run sudo without password
    sudo bash -c "echo \"$USER ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers"
}

function user-cancel() {
    echo ""
    popd > /dev/null
    exit 0
}

function devenv-pull() {
    if [ ! -d "$HOME/NVIDIA/BIN" ]; then
        echo "ERROR: $HOME/NVIDIA/BIN IS MISSING"
        exit 1
    fi
    
    pushd "$HOME/NVIDIA/BIN" > /dev/null
    git pull $NVIDIA_BIN_URL master
    popd > /dev/null 
}

function devenv-push() {
    if [ ! -d "$HOME/NVIDIA/BIN" ]; then
        echo "ERROR: $HOME/NVIDIA/BIN IS MISSING"
        exit 1
    fi
    
    pushd "$HOME/NVIDIA/BIN" > /dev/null
    du -sh * | sort -rh
    echo ""

    trap user-cancel INT
    read -r -n 1 -p "PRESS [ENTER] TO CONTINUE OR CTRL-C TO CANCEL: "
    echo ""
    
    git add .
    git commit -m "$(date)"
    git push --set-upstream $NVIDIA_BIN_URL master
    popd > /dev/null
}

function devenv-zerotier-join() {
    curl -s https://install.zerotier.com | sudo bash
    sudo systemctl enable zerotier-one.service
    sudo zerotier-cli join db64858fed3b37c1
}

while [ -n "$1" ]; do
    case "$1" in
        help)
            echo "USAGE: devenv [help] [init] [pull] [push] [zerotier] [ssh-keys]"
            echo "    help: show this message"
            echo "    init: initialize devenv"
            exit 0
        ;;
    
        init)
            devenv-init
        ;;
        
        pull)
            devenv-pull
        ;;
        
        push)
            devenv-push
        ;;
        
        zerotier)
            devenv-zerotier-join
        ;;
        
        *)
            echo "ERROR: UNKNOWN ARGUMENT: $1" > /dev/stderr
            devenv help
        ;;
    esac
    shift
done
    
