#!/bin/bash
function download() {
    if [ "$1" = "" ]; then
        return 1
    fi

    CL="$1"
    URL="http://linuxqa.nvidia.com/dvsbuilds/gpu_drv_dev_a_Release_Linux_AMD64_unix-build_Test_Driver/SW_$CL.0_gpu_drv_dev_a_Release_Linux_AMD64_unix-build_Test_Driver.tgz/NVIDIA-Linux-x86_64-DVS.run"

    axel -n30 $URL -o /tmp/NVIDIA-DVS-$CL.run && (
        ln -s -f "/tmp/NVIDIA-DVS-$CL.run" "/tmp/LAST-DOWNLOAD"
    )
}

while [ -n "$1" ]; do
    case "$1" in
        help)
            echo "USAGE: dvsbuild [help] [download CL]"
            exit 0
        ;;

        download)
            shift
            download $1
        ;;
        
        *)
            echo "ERROR: UNKNOWN ARGUMENT: $1" > /dev/stderr
            dvsbuild help
        ;;
    esac
    shift
done

