#!/bin/bash
function download() {
    INSTALL=0
    
    while [ -n "$1" ]; do
        case "$1" in
            -i|--install)
                INSTALL=1
            ;;
            
            [0-9]*)
                CL="$1"
            ;;
        esac
        shift
    done
    
    if [ "$CL" = "" ]; then
        echo "ERROR: CHANGELIST NUMBER IS MISSING" > /dev/stderr
        return 1
    fi

    URL="http://linuxqa.nvidia.com/dvsbuilds/gpu_drv_dev_a_Release_Linux_AMD64_unix-build_Test_Driver/SW_$CL.0_gpu_drv_dev_a_Release_Linux_AMD64_unix-build_Test_Driver.tgz/NVIDIA-Linux-x86_64-DVS.run"

    wget $URL -O /tmp/NVIDIA-DVS-$CL.run && (
        chmod 777 "/tmp/NVIDIA-DVS-$CL.run" 
        ln -s -f "/tmp/NVIDIA-DVS-$CL.run" "/tmp/LAST_DOWNLOAD"
        if [ "$INSTALL" = "1" ]; then
            nvidia-install "/tmp/NVIDIA-DVS-$CL.run"
        fi
    )
}

if [ -z "$1" ]; then
    echo "USAGE: dvsbuild [download CL [-i]]"
    exit 1
fi

while [ -n "$1" ]; do
    case "$1" in
        download)
            shift
            download $@
            exit 0
        ;;
        
        *)
        echo "ERROR: UNKNOWN COMMAND: $1" > /dev/stderr
        exit 1
    esac
    shift
done


