#!/bin/bash
DVSBUILD_DOWNLOADS="$HOME/NVIDIA/DVSBuild-Downloads"
mkdir -p "$DVSBUILD_DOWNLOADS"

function dvsbuild-download() {
    URL=""
    OUT=""
    INSTALL=0
    
    while [ -n "$1" ]; do
        case "$1" in
            -i|--install)
                INSTALL=1
            ;;
            
            dev_a)
                shift
                CL="$1"
                URL="http://linuxqa.nvidia.com/dvsbuilds/gpu_drv_dev_a_Release_Linux_AMD64_unix-build_Test_Driver/SW_$CL.0_gpu_drv_dev_a_Release_Linux_AMD64_unix-build_Test_Driver.tgz/NVIDIA-Linux-x86_64-DVS.run"
                OUT="$DVSBUILD_DOWNLOADS/NVIDIA-DEV_A-$CL.run"
                echo "Downloading: $OUT"
            ;;
            
            release)
                shift
                ID="$1"
                SUFFIX=""
                URL_PATCH=""
                if [[ $ID == *":dev"* ]]; then
                    ID="${ID%:*}"
                    SUFFIX=":dev"
                fi
                if [ "$SUFFIX" = ":dev" ]; then
                    URL_PATCH="/develop"
                fi
                URL="http://linuxqa/builds/release/display/x86_64$URL_PATCH/$ID/NVIDIA-Linux-x86_64-$ID.run"
                OUT="$DVSBUILD_DOWNLOADS/NVIDIA-RELEASE-$ID$SUFFIX.run"
                echo "Downloading: $OUT"
            ;;
            
            [0-9]*)
                
            ;;
        esac
        shift
    done
    
    if [ "$URL" = "" -o "$OUT" = "" ]; then
        dvsbuild # Show usage
        exit 1
    fi
    
    if [ -f "$OUT" ]; then
        echo "Reuse cache: $OUT"
        chmod 777 "$OUT" 
    else
        wget $URL -O "$OUT" && (
            chmod 777 "$OUT" 
            ln -s -f "$OUT" "$DVSBUILD_DOWNLOADS/LAST_DOWNLOAD"
        ) || (
            INSTALL=0
        )
    fi
    
    if [ "$INSTALL" = "1" ]; then
        nvidia-install "$OUT"
    fi
}

## MAIN

if [ -z "$1" ]; then
    echo "Usage: dvsbuild [download [dev_a CL] [release ID[:dev]] [-i]]"
    echo "  e.g. dvsbuild download dev_a CL"
    echo "  e.g. dvsbuild download release ID"
    echo "  e.g. dvsbuild download release ID:dev"
    exit 1
fi

while [ -n "$1" ]; do
    case "$1" in
        download)
            shift
            dvsbuild-download $@
            exit 0
        ;;
        
        *)
        echo "Error: Unknown command: $1" > /dev/stderr
	dvsbuild
        exit 1
    esac
    shift
done


