#!/bin/bash
NVBRANCH="sw/dev/gpu_drv/dev_a"

function nvinfo-libs() {
    FLAG_ALL=0
    FILTER=""
    
    while [ -n "$1" ]; do
        case "$1" in
            opengl)
                FOLDER="$P4ROOT/$NVBRANCH/drivers/OpenGL"
            ;;
            
            -f|--filter)
                shift
                FILTER="$1"
            ;;
        esac
        shift
    done
    
    if [ ! -d "$FOLDER" ]; then
        FOLDER="$P4ROOT/$NVBRANCH"
    fi
    
    echo "" > /tmp/nvinfo.libs
    find "$FOLDER" -type f -name "*.so" > "/tmp/nvinfo.libs" && (
        while read LINE; do
            if [ ! -z "$FILTER" ]; then
                if [[ $LINE == *"$FILTER"* ]]; then
                    echo "${LINE/$P4ROOT\/$NVBRANCH\//''}"
                fi
            else
                echo "${LINE/$P4ROOT\/$NVBRANCH\//''}"
            fi
        done < "/tmp/nvinfo.libs"
    ) || (
        echo "Error: Failed to find NVIDIA libs in $FOLDER"
        return 1
    )
}

nvinfo-libs $@

