#!/bin/bash
NVBRANCH="sw/dev/gpu_drv/dev_a"

function dist-install() {
    INSTALLER=$([ "$1" = "" ] && echo "$HOME/NVIDIA-BUILD/LAST_BUILD" || echo "$1")
    if [ ! -f "$INSTALLER" ]; then
        echo "ERROR: INSTALLER IS MISSING: $INSTALLER" > /dev/stderr
        return 1
    fi

    sudo chmod +x "$INSTALLER"

    echo "NVIDIA INSTALL: $INSTALLER"
    who am i > /dev/null && (
        sudo systemctl isolate multi-user
        sudo "$INSTALLER" -sb
        sudo systemctl isolate graphical
    ) || echo "ERROR: YOU CAN ONLY RUN INSTALLER ON SSH" > /dev/stderr 
}

function nvidia-source-version() {
    echo `grep '^#define NV_VERSION_STRING' $P4ROOT/$NVBRANCH/drivers/common/inc/nvUnixVersion.h  | awk '{print $3}' | sed 's/"//g'`
}

function nvidia-version-installed() {
    if [ "$1" = "" ]; then
        echo "USAGE: nvidia-version-installed <ARCH>" > /dev/stderr
        return 1
    fi

    ARCH="$1"
    ARCHNAME=$([ "$ARCH" = "amd64" ] && echo "x86_64" || echo "i386")
    SOFILE=$(ls /usr/lib/$ARCHNAME-linux-gnu/libnvidia-glcore.so* | head -n 1)
    POS=$([ "$ARCH" = "amd64" ] && echo "46" || echo "44")
    LEN=$(( ${#SOFILE} - POS ))
    VERSION="${SOFILE:$POS:$LEN}"

    if [ -f "/usr/lib/$ARCHNAME-linux-gnu/libnvidia-glvkspirv.so.$VERSION" ]; then
        echo "$VERSION"
    else
        echo "ERROR: FAILED TO PARSE NVIDIA VERSION INSTALLED: $VERSION" > /dev/stderr
        return 1
    fi
}

function module-install() {
    if [ "$1" = "" -o "$2" = "" -o "$3" = "" ]; then
        echo "USAGE: module-install [MODULE] [ARCH] [BUILD_TYPE]" > /dev/stderr
        return 1
    fi

    MODULE="$1" && shift
    ARCH="$1" && shift
    BUILD_TYPE="$1" && shift 
    FOLDER="Linux_"$ARCH"_$BUILD_TYPE"

    if [ "$(nvidia-source-version)" != "$(nvidia-version-installed $ARCH)" ]; then  
        echo "ERROR: \"SOURCE VERSION [$(nvidia-source-version)]\" != \"INSTALLED VERSION [$(nvidia-version-installed $ARCH)]\"" > /dev/stderr
        return 1
    fi

    echo "NVIDIA INSTALL: $MODULE $ARCH $BUILD_TYPE"
    case "$MODULE" in
        opengl)
            FOLDER="Linux_"$ARCH"_$BUILD_TYPE"
            OUTDIR="$P4ROOT/$NVBRANCH/drivers/OpenGL/_out/$FOLDER"
            BASENAME="libnvidia-glcore.so"
            VERSION=$(nvidia-source-version)
            ARCHNAME=$([ "$ARCH" = "amd64" ] && echo "x86_64" || echo "i386")
            TARGETNAME="/usr/lib/$ARCHNAME-linux-gnu/$BASENAME.$VERSION"
            
            if [ -f "$TARGETNAME" -o -L "$TARGETNAME" ]; then
                if [ ! -f "$TARGETNAME.backup" ]; then
                    sudo mv "$TARGETNAME" "$TARGETNAME.backup"
                fi
                sudo cp -f "$OUTDIR/$BASENAME" "$TARGETNAME"
            else
                echo "ERROR: $TARGETNAME IS MISSING" > /dev/stderr
                return 1
            fi

            echo "BACKUP & UPDATE: $TARGETNAME"
        ;;

        *)
            echo "ERROR: MODULE \"$MODULE\" IS NOT SUPPORTED" > /dev/stderr
            return 1
        ;;
    esac 
}

function module-revert() {
    if [ "$1" = "" ]; then
        echo "USAGE: module-revert [ARCH]" > /dev/stderr
        return 1
    fi

    ARCH="$1" && shift
    ARCHNAME=$([ "$ARCH" = "amd64" ] && echo "x86_64" || echo "i386")
    FOLDER="/usr/lib/$ARCHNAME-linux-gnu"

    for FILE in `ls $FOLDER/*.backup`; do
        sudo mv -f "$FILE" "${FILE%.*}"
        echo "REVERTED: ${FILE%.*}"
    done
}

if [ "$1" = "" ]; then
    echo "USAGE 1: nvidia-install <INSTALLER_PATH>"
    echo "USAGE 2: nvidia-install <MODULE> <ARCH> <BUILD_TYPE>"
    echo "USAGE 3: nvidia-install <-r|--revert> <ARCH>"
    exit 1
fi

while [ -n "$1" ]; do
    case "$1" in
        opengl)
            shift
            module-install opengl $@
            break
        ;;

        -r|--revert)
            shift
            module-revert $@
            break
        ;;

        *)
            if [ -f "$1" -o -L "$1" ]; then
                dist-install "$1"
                break
            else
                echo "ERROR: INSTALLER IS MISSING: $1" > /dev/stderr
                exit 1
            fi
        ;;
    esac
    shift
done
