#!/bin/bash
NVBRANCH="sw/dev/gpu_drv/dev_a"

function dist-install() {
    INSTALLER=$([ "$1" = "" ] && echo "$HOME/NVIDIA-BUILD/LAST_BUILD" || echo "$1")
    if [ ! -f "$INSTALLER" ]; then
        echo "ERROR: INSTALLER IS MISSING: $INSTALLER" > /dev/stderr
        return 1
    fi

    echo "NVIDIA INSTALL: $INSTALLER"
    who am i > /dev/null && (
        sudo systemctl isolate multi-user
        sudo "$INSTALLER" -sb
        sudo systemctl isolate graphical
    ) || echo "ERROR: YOU CAN ONLY RUN INSTALLER ON SSH" > /dev/stderr 
}

function module-install() {
    if [ "$1" = "" -o "$2" = "" -o "$3" = "" ]; then
        echo "USAGE: module-install [MODULE] [ARCH] [BUILD_TYPE]" > /dev/stderr
        return 1
    fi

    MODULE="$1"
    ARCH="$2"
    BUILD_TYPE="$3"
    FOLDER="Linux_"$ARCH"_$BUILD_TYPE"
    VERSION=$(nvidia-source-version)

    echo "NVIDIA INSTALL: $MODULE $ARCH $BUILD_TYPE"
    case "$MODULE" in
        opengl)
            FOLDER="Linux_"$ARCH"_$BUILD_TYPE"
            OUTDIR="$P4ROOT/$NVBRANCH/drivers/OpenGL/_out/$FOLDER"
            FILENAME="libnvidia-glcore.so"
            VERSION=$(nvidia-source-version)
            ARCHNAME=$([ "$ARCH" = "amd64" ] && echo "x86_64" || echo "i386")
            TARGETNAME="/usr/lib/$ARCHNAME-linux-gnu/$FILENAME.$VERSION"
            
            sudo cp -f "$OUTDIR/$FILENAME" "$TARGETNAME"
            echo "UPDATED: $TARGETNAME"
        ;;

        *)
            echo "ERROR: MODULE \"$MODULE\" IS NOT SUPPORTED" > /dev/stderr
            return 1
        ;;
    esac 
}

if [ "$1" = "" ]; then
    echo "USAGE 1: nvidia-install <MODULE> <ARCH> <BUILD_TYPE>"
    echo "USAGE 2: nvidia-install <INSTALLER_PATH>"
    exit 1
fi

while [ -n "$1" ]; do
    case "$1" in
        opengl)
            shift
            ARCH="$1"
            shift
            BUILD_TYPE="$1"

            module-install opengl "$ARCH" "$BUILD_TYPE"
        ;;

        *)
            if [ -f "$1" -o -L "$1" ]; then
                dist-install "$1"
            else
                echo "ERROR: INSTALLER IS MISSING: $1" > /dev/stderr
                exit 1
            fi
        ;;
    esac
    shift
done
