#!/bin/bash
NVBRANCH="sw/dev/gpu_drv/dev_a"

# function nvidia-sofiles() {
#     if [ "$NVBLD_SWEEP" = "1" ]; then
#         return
#     fi
# 
#     if [ ! -f "$NVBUILD_LOCK" ]; then
#         echo "ERROR: FILE $NVBUILD_LOCK IS MISSING" > /dev/stderr
#         return 1
#     fi
# 
#     mkdir -p "$NVBUILD_OUT"
#     find "`pwd`" -type f -newer "$NVBUILD_LOCK" \( -name "*.so" -o -name "*.so.*" \) > "$NVBUILD_SO_FILES" || (
#         echo "ERROR: FAILED TO FIND NVIDIA SO FILES"
#     )
#     
#     echo "NVIDIA SO FILES: [$(wc -l < $NVBUILD_SO_FILES) GENERATED]"
#     
#     # echo "[$(wc -l < $NVBLD_MODULES_FILE) FILES FOUND]"
#     # 
#     # head -9 "$NVBLD_MODULES_FILE" |
#     # while read LINE; do
#     #     echo $LINE
#     # done
#     # 
#     # if [ $(wc -l < $NVBLD_MODULES_FILE) -gt 9 ]; then
#     #     echo "..."
#     # fi
# }

function dist-install() {
    INSTALLER=$([ "$1" = "" ] && echo "$HOME/NVIDIA-BUILD/LAST_BUILD" || echo "$1")
    if [ ! -f "$INSTALLER" ]; then
        echo "ERROR: INSTALLER IS MISSING: $INSTALLER" > /dev/stderr
        return 1
    fi

    echo "NVIDIA INSTALL: $INSTALLER"
    who am i > /dev/null && (
        sudo systemctl isolate multi-user
        sudo "$INSTALLER" -sb
        sudo systemctl isolate graphical
    ) || echo "ERROR: YOU CAN ONLY RUN INSTALLER ON SSH" > /dev/stderr 
}

function module-install() {
    if [ "$1" = "" -o "$2" = "" -o "$3" = "" ]; then
        echo "USAGE: module-install [ARCH] [BUILD_TYPE] [MODULE]" > /dev/stderr
        return 1
    fi

    ARCH="$1"
    BUILD_TYPE="$2"
    MODULE="$3"
    FOLDER="Linux_"$ARCH"_$BUILD_TYPE"
    VERSION=$(nvidia-source-version)

    case "$MODULE" in
        opengl)
            FOLDER="Linux_"$ARCH"_$BUILD_TYPE"
            OUTDIR="$P4ROOT/$NVBRANCH/drivers/OpenGL/_out/$FOLDER"
            FILENAME="libnvidia-glcore.so"
            VERSION=$(nvidia-source-version)
            ARCHNAME=$([ "$ARCH" = "amd64" ] && echo "x86_64" || echo "i386")
            TARGETNAME="/usr/lib/$ARCHNAME-linux-gnu/$FILENAME.$VERSION"
            
            sudo cp -f "$OUTDIR/$FILENAME" "$TARGETNAME"
            echo "==> $TARGETNAME"
        ;;

        *)
            echo "ERROR: MODULE \"$MODULE\" IS NOT SUPPORTED" > /dev/stderr
            return 1
        ;;
    esac 
}