#!/bin/bash
NVBRANCH="sw/dev/gpu_drv/dev_a"

function libs-list() {
    FLAG_ALL=0
    FILTER=""
    
    while [ -n "$1" ]; do
        case "$1" in
            opengl)
                FOLDER="$P4ROOT/$NVBRANCH/drivers/OpenGL"
            ;;
            
            -f|--filter)
                shift
                FILTER="$1"
            ;;
            
            *)
                if [ ! -d "$FOLDER" ]; then
                    echo "ERROR: FOLDER IS MISSING: $FOLDER" > /dev/stderr
                    return 1
                fi
            ;;
        esac
        shift
    done
    
    if [ -z "$FOLDER" ]; then
        FOLDER="$P4ROOT/$NVBRANCH"
    fi
    
    echo "" > /tmp/LIBS_LIST
    find "$FOLDER" -type f -name "*.so" > "/tmp/LIBS_LIST" && (
        while read LINE; do
            if [ ! -z "$FILTER" ]; then
                if [[ $LINE == *"$FILTER"* ]]; then
                    echo "${LINE/$P4ROOT\/$NVBRANCH\//''}"
                fi
            else
                echo "${LINE/$P4ROOT\/$NVBRANCH\//''}"
            fi
        done < "/tmp/LIBS_LIST"
    ) || (
        echo "ERROR: FAILED TO FIND NVIDIA LIBS IN $FOLDER"
        return 1
    )
}

libs-list $@

