#!/bin/bash
if [ "$1" = "" -o "$2" = "" ]; then
    echo "Usage: p4sync <MODULE> <CL>"
    exit 1
fi

case "$1" in
    dev_a)  MODULE="//sw/dev/gpu_drv/dev_a/..." ;;
    opengl) MODULE="//sw/dev/gpu_drv/dev_a/drivers/OpenGL/..." ;;
    *) echo "Error: Module \"$1\" is not supported" > /dev/stderr && exit 1 ;;
esac

CL="$2"
p4 sync $MODULE@$CL
