#!/bin/bash

IFS=":" ELEMENTS=($PATH)
for ELEMENT in "${ELEMENTS[@]}"; do 
    if [ ! -d "$ELEMENT" ]; then
        continue
    fi
    
    FOUND_PATH=$(find "$ELEMENT" -type f -name "$1" -print -quit)
    if [ ! -z "$FOUND_PATH" ]; then
        echo "$FOUND_PATH"
        exit 0
    fi
done

exit 1
