#!/bin/bash

function motherboard-name() {
    echo ""
}

function cpu-name() {
    echo ""
}

# https://serverfault.com/questions/235825/disable-hyperthreading-from-within-linux-no-access-to-bios
# lscpu --all --extended
# cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list | sort -n | uniq
function cpu-hyperthreading-info() {
    case "$1" in
        --enable)
        ;;
        --disable)
        ;;
        *)
	;;
    esac
}

function cpu-prefetch-info() {
    echo ""
}

function ram-size() {
    echo ""
}

function ssd-size() {
    echo ""
}

function hdd-size() {
    echo ""
}

function system-name() {
    echo ""
}

function xserver-info() {
    echo ""
}

function xwindow-info() {
    echo ""
}

function gpu-name() {
    echo ""
}

function gpu-vram-size() {
    echo ""
}

function gpu-driver() {
    echo ""
}

function opengl-version() {
    echo ""
}

function vulkan-version() {
    echo ""
}

function monitor-name() {
    echo ""
}

function monitor-resolution() {
    echo ""
}

function monitor-color-depth() {
    echo ""
}

function sysinfo-show() {
    echo "       Hardware"
    echo "==============="
    echo "   Motherboard: $(motherboard-name)"
    echo "      CPU Name: $(cpu-name)"
    echo "Hyperthreading: $(cpu-hyperthreading-info)"
    echo "      Prefetch: $(cpu-prefetch-info)"
    echo "           RAM: $(ram-size)"
    echo "           SSD: $(ssd-size)"
    echo "           HDD: $(hdd-size)"
    echo ""

    echo "         System"
    echo "==============="
    echo "          Name: $(system-name)"
    echo "        Kernel: $(uname -r)"
    echo "      X Server: $(xserver-info)"
    echo "      X Window: $(xwindow-info)"
    echo ""
    
    echo "     Video Card"
    echo "==============="
    echo "          Name: $(gpu-name)"
    echo "          VRAM: $(gpu-vram-size)"
    echo "        Driver: $(gpu-driver)"
    echo "    OpenGL API: $(opengl-version)"
    echo "    Vulkan API: $(vulkan-version)"
    echo "       Monitor: $(monitor-name)"
    echo "    Resolution: $(monitor-resolution)"
    echo "   Color Depth: $(monitor-color-depth)"
    echo ""
}

while [ -n "$1" ]; do
    case "$1" in
        enable-ht|enable-hyperthreading)
            cpu-hyperthreading-info --enable
            exit 0
        ;;

        disable-ht|disable-hyperthreading)
            cpu-hyperthreading-info --disable
            exit 0
        ;;
    esac
    shift
done

sysinfo-show

