#!/bin/bash

# Set up desktop links
if [ ! -e "$HOME/Desktop/BIN" ]; then
    ln -s "$HOME/NVIDIA/BIN" "$HOME/Desktop/BIN"
fi

if [ ! -e "$HOME/Desktop/MARKDOWN" ]; then
    ln -s "$HOME/NVIDIA/BIN/DOC/MARKDOWN" "$HOME/Desktop/MARKDOWN"
fi

if [ ! -e "$HOME/Desktop/DEV_A" ]; then
    ln -s "$P4ROOT/sw/dev/gpu_drv/dev_a" "$HOME/Desktop/DEV_A"
fi

if [ ! -e "$HOME/Desktop/OPENGL" ]; then
    ln -s "$P4ROOT/sw/dev/gpu_drv/dev_a/drivers/OpenGL" "$HOME/Desktop/OPENGL"
fi

# Select the first GNOME window
which xdotool > /dev/null || sudo apt install -y xdotool
xdotool mousemove 0 0 click 1

