#!/bin/bash
# Vulkan
# 2560x1440

# Launch steam if it's not currently running
pgrep -x steam >/dev/null && echo "STEAM IS RUNNING..." || (
    gnome-terminal -- bash -c "steam || echo \"$(date)\" >> $HOME/FAILED_TO_START_STEAM"
    sleep 15
)

if ! [[ -f "$HOME/.steam/steam/steamapps/common/The Talos Principle/Bin/x64/Talos" ]]; then
    echo "INSTALL Talos Principle IN STEAM'S WINDOW AND TRY AGAIN"
    exit 1
fi

PRIME_NO_RUN=1
source prime-run
PRIME_NO_RUN=""

case "$1" in
    -d|--direct)
        ~/.steam/steam/steamapps/common/The\ Talos\ Principle/Bin/x64/Talos +gfx_strAPI VLK +gfx_pixResWidth 2560 +gfx_pixResHeight 1440 +exec ~/.phoronix-test-suite/installed-tests/pts/talos-principle-1.2.1/talos-run-test.lua
    ;;
    
    *)
        (echo 2; echo 7; echo n) | phoronix-test-suite benchmark pts/talos-principle
    ;;
esac
